# docker-compose.yml
# Add this top-level entry
redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  build: ./
  volumes:
    - ./:/var/www/app
  ports:
    - 8080:8080
  environment:
    - NODE_ENV=development
    - PORT=8080
    - REDIS_URL=redis://cache
  links:
    - redis  
  command:
    sh -c 'npm i && node server.js'